########################################
# Derived from gprom travis build image which supports all backends
########################################
FROM iitdbgroup/gprom_travis
MAINTAINER Boris Glavic <bglavic@iit.edu>
########################################
# Install extra packages for experiments
########################################
RUN apt-get -y update && apt-get install -y \
    ghostscript \
    gnuplot \
    python3 \
    postgresql \
    python3-pip \
    sudo \
    wget \
	&& rm -rf /var/lib/apt/lists/*
########################################
# Clone and install temporal postgres
########################################
ADD tpg_quickbuild.sh /scripts/tpg-install.sh
RUN mkdir -p /tpg /servers /data \
    && chown -R postgres /tpg /servers /scripts/tpg-install.sh /data
USER postgres
RUN cd /tpg \
    && wget http://tpg.inf.unibz.it/downloads/postgresql-9.6beta3-temporal.tar.gz \
    && tar xzf postgresql-9.6beta3-temporal.tar.gz \
    && /scripts/tpg-install.sh
########################################
# Setup clusters for normal postgres
########################################
RUN mkdir -p /data/postgres \
    && /usr/lib/postgresql/9.5/bin/initdb -D /data/postgres
########################################
# Load data
########################################
#TODO